Enable subscription module configuration in dev-plb-root

diff --git a/pipeline/templates/deploy-terraform.yaml b/pipeline/templates/deploy-terraform.yaml
--- a/pipeline/templates/deploy-terraform.yaml
+++ b/pipeline/templates/deploy-terraform.yaml
@@ -51,7 +51,11 @@ stages:
                 echo "ARM_USE_OIDC: $ARM_USE_OIDC"
                 
                 terraform init -upgrade
-
+                # Unlock state if locked (replace with actual lock ID from error if different)
+                # terraform force-unlock -force 9e7650ec-40e9-c190-f1b2-43bcbaec65a2 || echo "Lock already released or unlock failed, continuing..."
+                
+                # terraform import 'module.subscription["plb-papliba-test-001"].module.sub_move.azurerm_management_group_subscription_association.sub_move' '/providers/Microsoft.Management/managementGroups/test-corp|/subscriptions/ea4a2edd-9860-49ae-bf7c-d58e4f1a260d'
+                
                 terraform plan
 
   # Apply Stage
@@ -98,9 +102,4 @@ stages:
                       echo "ARM_USE_OIDC: $ARM_USE_OIDC"
                       
                       terraform init -upgrade
-                      
-                      if [ "${{ parameters.runPlanInApply }}" = "true" ]; then
-                        terraform plan
-                      fi
-
                       terraform apply -auto-approve
